package units;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import org.pm.Props;

public class PropsTest {
    @Test public void testSomeLibraryMethod() {
       
        System.out.println(Props.property("dd"));
    
    }
}
