package units;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import org.props.Reader;

public class PropsTest {
    @Test public void testSomeLibraryMethod() {
       
        System.out.println(Reader.property("hello"));
        System.out.println(Reader.property("hello", "smoke.properties"));
    
    }
}
